force-app/main/default/objects/Currency_Layer_Tracker__c/Currency_Layer_Tracker__c.object-meta.xml
<CustomObject>
    <label>Currency Layer Tracker</label>
    <nameField>
        <displayFormat>CLT-{yyyy}-{mm}-{dd}-{0}</displayFormat>
        <label>Currency Layer Tracker</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Currency Layer Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Currency_Layer_Tracker__c/fields/Start_Value__c.field-meta.xml
<CustomField>
    <fullName>Start_Value__c</fullName>
    <label>1 Dollars In Rupees</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Future_Schedule_CallOut_Example.cls
public class Future_Schedule_CallOut_Example {
    @future(callout=true)
    public static void show(String apiKey){
         Decimal inrValue;
         List<Currency_Layer_Tracker__c> currencyListUpdate = new List<Currency_Layer_Tracker__c>();
         Http hp = new Http();
         HttpRequest request = new HttpRequest();
         String endPoint ='http://api.currencylayer.com/live?';
         endPoint = endPoint+'access_key='+apiKey;
         endPoint = endPoint+'&currencies=INR&source=USD&format=1';
         request.setEndpoint(endpoint);
         request.setMethod('GET');
         HttpResponse response = hp.send(request);
         String jsonString = response.getBody();
         System.JSONParser jp = JSON.createParser(jsonString);
         While(jp.nextToken()!=null){
             if(jp.getText()=='USDINR'){
                 jp.nextToken();
                 inrValue = (Decimal)jp.getDecimalValue();
             }
        }
        
        Currency_Layer_Tracker__c currencyVal = new Currency_Layer_Tracker__c();
        insert currencyVal;
        List<Currency_Layer_Tracker__c> currencyList= [select id,name,Start_Value__c from Currency_Layer_Tracker__c WHERE id=:currencyVal.id];
        for(Currency_Layer_Tracker__c con : currencyList){
            inrValue = Math.round(inrValue * 100) / 100.0;
            con.Start_Value__c = inrValue+' Indian Rupee'; 
            currencyListUpdate.add(con);
        }
        
        if(currencyListUpdate.size()>0){
           update currencyListUpdate; 
        }
        

    }

}