force-app/main/default/objects/X100Dayscodechallanges__c/X100Dayscodechallanges__c.object-meta.xml
<CustomObject>
    <label>#100Dayscodechallanges</label>
    <nameField>
        <displayFormat>Day-{00000}</displayFormat>
        <label>#100Dayscodechallanges Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>100Dayscodechallanges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/X100Dayscodechallanges__c/fields/Enter_Palindrome_Number__c.field-meta.xml
<CustomField>
    <fullName>Enter_Palindrome_Number__c</fullName>
    <label>Enter Palindrome Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X100Dayscodechallanges__c/fields/isPalindrome__c.field-meta.xml
<CustomField>
    <fullName>isPalindrome__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isPalindrome</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PalindromeExample2.cls
// A palindrome String is a String that is same after reverse. 
// Example- It can also be a string like LOL, MADAM etc.
// 
public class PalindromeExample2 {
    public static void checkPalindrome(String str){
        String tempString = str.reverse(); 
        if(tempString == str){
           if(str!=null){
               X100Dayscodechallanges__c pm = new X100Dayscodechallanges__c();
               pm.Enter_Palindrome_Number__c = str;
               pm.isPalindrome__c = true;
               insert pm; 
       	  }
        }else{
            X100Dayscodechallanges__c pm = new X100Dayscodechallanges__c();
            pm.Enter_Palindrome_Number__c = str;
            pm.isPalindrome__c = false;
            insert pm; 
        }
    }
}