force-app/main/default/objects/X100Dayscodechallanges__c/X100Dayscodechallanges__c.object-meta.xml
<CustomObject>
    <label>#100Dayscodechallanges</label>
    <nameField>
        <displayFormat>Day-{00000}</displayFormat>
        <label>#100Dayscodechallanges Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>100Dayscodechallanges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/X100Dayscodechallanges__c/fields/Enter_Palindrome_Number__c.field-meta.xml
<CustomField>
    <fullName>Enter_Palindrome_Number__c</fullName>
    <label>Enter Palindrome Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X100Dayscodechallanges__c/fields/isPalindrome__c.field-meta.xml
<CustomField>
    <fullName>isPalindrome__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isPalindrome</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PalindromeExample1.cls
/*
 * A palindrome number is a number that is same after reverse. For example 545, 151, 34543, 343, 171, 48984 are the palindrome numbers. 
 * It can also be a string like LOL, MADAM etc.
 */
public class PalindromeExample1 {
    Public static Integer result;
    Public static Integer sum=0;
    Public static Integer temp;
    public static void checkPalindrome(Integer num){
        if(num!=null){
           X100Dayscodechallanges__c pm = new X100Dayscodechallanges__c();
           pm.Enter_Palindrome_Number__c = String.valueOf(num);
           pm.isPalindrome__c = isPalindromeExample(num);
           insert pm; 
        }
        
    }
    public static boolean isPalindromeExample(Integer num){
        temp = num;
        System.debug('Temp=>' + temp);
        while(num>0){    
            result = Math.mod(num, 10);//getting remainder
            System.debug('result =>' + result);  
            sum = (sum*10) + result;    
            System.debug('sum =>' + sum);
            num = num / 10;
            System.debug('num =>' + num); 
        }
        if(temp==sum){
            System.debug(num + ' is an Palindrome Number');
            return true;
        }else{     
            System.debug(num + ' is not Palindrome Number'); 
            return false;
        }  
    }
}