force-app/main/default/objects/X100Dayscodechallanges__c/X100Dayscodechallanges__c.object-meta.xml
<CustomObject>
    <label>#100Dayscodechallanges</label>
    <nameField>
        <displayFormat>Day-{00000}</displayFormat>
        <label>#100Dayscodechallanges Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>100Dayscodechallanges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/X100Dayscodechallanges__c/fields/Enter_Armstrong_Number__c.field-meta.xml
<CustomField>
    <fullName>Enter_Armstrong_Number__c</fullName>
    <label>Enter Armstrong Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X100Dayscodechallanges__c/fields/isArmstrongNumber__c.field-meta.xml
<CustomField>
    <fullName>isArmstrongNumber__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isArmstrongNumber</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ArmstrongExample2.cls
/*
 * checks if the given number is an Armstrong number or not.
 *  abcd... = an + bn + cn + dn + ...
 */ 
public class ArmstrongExample2 {
    public static void checkArmstrongNumber(long armstrongNumber){
        if(isArmstrong(armstrongNumber)){
            X100Dayscodechallanges__c pm = new X100Dayscodechallanges__c();
            pm.Enter_Armstrong_Number__c = String.valueOf(armstrongNumber);
            pm.isArmstrongNumber__c = true; //isArmstrong(armstrongNumber);
            insert pm; 
            System.debug(armstrongNumber + ', Armstrong Number');
        }else{
            X100Dayscodechallanges__c pm = new X100Dayscodechallanges__c();
            pm.Enter_Armstrong_Number__c = String.valueOf(armstrongNumber);
            pm.isArmstrongNumber__c = true; //isArmstrong(armstrongNumber);
            insert pm; 
            System.debug(armstrongNumber + ', Not Armstrong Number'); 
        }
    }
    public static boolean isArmstrong(long num){
        long temp=0, digits=0, last=0, sum=0;
        temp = num;
        while(temp>0){   
        temp = temp/10;    
        digits++;   
      }   
      temp = num;   
      while(temp>0){    
         last = Math.mod(temp, 10); //temp % 10;   
         sum = sum + (long)(Math.pow(last, digits));     
         temp = temp/10;
      }
        
        if(num==sum){
            return true;
        }else{
            return false;
        }
    }
}