force-app/main/default/objects/X100Dayscodechallanges__c/X100Dayscodechallanges__c.object-meta.xml
<CustomObject>
    <label>#100Dayscodechallanges</label>
    <nameField>
        <displayFormat>Day-{00000}</displayFormat>
        <label>#100Dayscodechallanges Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>100Dayscodechallanges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/X100Dayscodechallanges__c/fields/Enter_Prime_Number__c.field-meta.xml
<CustomField>
    <fullName>Enter_Prime_Number__c</fullName>
    <label>Enter Prime Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X100Dayscodechallanges__c/fields/isPrime_Number__c.field-meta.xml
<CustomField>
    <fullName>isPrime_Number__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isPrime Number</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CheckPrimeNumber.cls
/* Day-1
 * Prime number in Java: Prime number is a number that is greater than 1 and divided by 1 or itself only. In other words, 
 * prime numbers can't be divided by other numbers than itself or 1. For example 2, 3, 5, 7, 11, 13, 17.... are the prime numbers.
 * 
*/
public class CheckPrimeNumber {
    public static void checkPrime(Integer primeNumber){
        if(primeNumber!=null){
            X100Dayscodechallanges__c pm = new X100Dayscodechallanges__c();
            pm.Enter_Prime_Number__c = String.valueOf(primeNumber);
            pm.isPrime_Number__c = isPrime(primeNumber);
            insert pm;
        }
        if(isPrime(primeNumber)){
            System.debug(primeNumber + ' is a prime number');             
        }else{
            System.debug(primeNumber + ' is not a prime number');  
        }
    }
    public static boolean isPrime(Integer num){//4<=1
       if(num<=1){  
           return false;  
       }  
       for(integer i=2;i<=Math.sqrt(num); i++) { 
           if(Math.Mod(num,i)==0) { 
               return false;  
           }  
       }  
       return true;   
    }
}